In function 'test':
tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c:37:nn: warning: expected 3 vararg pointer(s); got 2 [enabled by default]
tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c:29:nn: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c.test-refcount-errors.html'
