Trace 0:
  Transitions:
  error: WrongNumberOfVarargs()
  error: expected 3 vararg pointer(s); got 2
  region for gcc.ParmDecl('self') on stack:
    repr(): RegionOnStack("region for gcc.ParmDecl('self')")
    str(): region for gcc.ParmDecl('self') on stack
    r->ob_refcnt: refs: 0 owned, 1 borrowed
    r->ob_type: PointerToRegion(gcctype='struct PyTypeObject *', loc=gcc.Location(file='tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c', line=28), region=Region("region-for-type-of-arg-gcc.ParmDecl('self')"))
  region for gcc.ParmDecl('args') on stack:
    repr(): RegionOnStack("region for gcc.ParmDecl('args')")
    str(): region for gcc.ParmDecl('args') on stack
    r->ob_refcnt: refs: 0 owned, 1 borrowed
    r->ob_type: PointerToRegion(gcctype='struct PyTypeObject *', loc=gcc.Location(file='tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c', line=28), region=Region("region-for-type-of-arg-gcc.ParmDecl('args')"))
  RegionForGlobal(gcc.VarDecl('_Py_NoneStruct')):
    repr(): RegionForGlobal(gcc.VarDecl('_Py_NoneStruct'))
    str(): RegionForGlobal(gcc.VarDecl('_Py_NoneStruct'))
    r->ob_refcnt: refs: 0 owned, 1 borrowed
    r->ob_type: None
  Exception:
    (struct PyObject *)0 from tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c:29
